# Tensors Basics

In [3]:
import torch
import numpy as np

In [4]:
torch.__version__

'1.5.0'

In [5]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
arr.dtype

dtype('int64')

In [10]:
x = torch.from_numpy(arr) # Creating tensor from numpy array

In [11]:
type(x)

torch.Tensor

In [12]:
torch.as_tensor(arr) # the other way of creating a tensor

tensor([1, 2, 3, 4, 5])

In [15]:
arr2d = np.arange(0.0, 12.0)
arr2d = arr2d.reshape(4,3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [16]:
x2 = torch.from_numpy(arr2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [18]:
arr

array([1, 2, 3, 4, 5])

In [19]:
x

tensor([1, 2, 3, 4, 5])

In [21]:
arr[0] = 99 # Now array is affected, which means that tensor created from the array is affected as well
# so called "Direct Link"
arr

array([99,  2,  3,  4,  5])

In [22]:
x

tensor([99,  2,  3,  4,  5])

In [24]:
# If we do not want a tensor to be affected by the changed array. Let's create a tensor without Direct Linking
my_arr = np.arange(0,10)
my_tensor = torch.tensor(my_arr)

In [25]:
my_other_tensor = torch.from_numpy(my_arr)

In [26]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
my_arr[0] = 9999
my_arr

array([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [30]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

## Tensors basics part 2

In [33]:
new_arr = np.array([1,2,3])
new_arr.dtype

dtype('int64')

In [42]:
torch.tensor(new_arr).dtype # tensor with small "t" creates int64 tensor. Infer the datatype from original array

torch.int64

In [41]:
torch.Tensor(new_arr).dtype # tensor with the capital "T" creates float32 tensor tensor.FloatTensor

torch.float32

### Creating tensors from scratch

In [43]:
torch.empty(2,2)

tensor([[4.1175e-35, 4.5699e-41],
        [1.3902e-36, 0.0000e+00]])

In [45]:
torch.zeros(4,3) # zeros(4,3,dtype=torch.int64)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [46]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [48]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [50]:
torch.linspace(0,18,12).reshape(4,3)

tensor([[ 0.0000,  1.6364,  3.2727],
        [ 4.9091,  6.5455,  8.1818],
        [ 9.8182, 11.4545, 13.0909],
        [14.7273, 16.3636, 18.0000]])

In [52]:
torch.tensor([1,2,3]) # normal python list

tensor([1, 2, 3])

In [60]:
my_tensor = torch.tensor([1,2,3])
my_tensor.dtype

torch.int64

In [63]:
my_tensor = my_tensor.type(torch.int32) # converting data type of a tensor
my_tensor.dtype

torch.int32

In [64]:
torch.rand(4,3)

tensor([[0.1364, 0.1315, 0.2825],
        [0.7509, 0.1751, 0.1849],
        [0.6631, 0.8303, 0.7818],
        [0.7108, 0.2397, 0.3760]])

In [65]:
torch.randn(4,3)

tensor([[-0.5680,  0.0254, -0.4274],
        [ 0.0830, -0.7859,  0.3467],
        [-0.7393,  0.3404, -1.0983],
        [ 1.9477, -1.4676, -1.5735]])

In [68]:
torch.randint(low=0, high=10, size=(5,5)) # high is exclusive

tensor([[2, 3, 7, 2, 6],
        [1, 8, 0, 8, 1],
        [1, 9, 2, 2, 9],
        [0, 2, 6, 4, 1],
        [6, 3, 5, 2, 7]])

In [69]:
x = torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [72]:
torch.rand_like(x) # returns a tensor like the tensor in x in shape

tensor([[0.1886, 0.1290, 0.9360, 0.0055, 0.0478],
        [0.1404, 0.2204, 0.3470, 0.2820, 0.0735]])

In [73]:
torch.randn_like(x)

tensor([[-0.2860, -0.4966,  0.6447,  0.4334,  1.0506],
        [ 1.1287, -0.6975, -0.6882, -0.4432,  0.3668]])

In [75]:
torch.randint_like(x,low=5, high=11)

tensor([[ 5.,  7., 10.,  7.,  9.],
        [ 7., 10., 10., 10.,  6.]])

In [86]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [87]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

### Tensor operations

In [88]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [90]:
x[1,1] # Grabbing entries of tensor

tensor(3)

In [95]:
x[:,1] # returns row-vector

tensor([1, 3, 5])

In [96]:
x[:,1:] # returns column-vector

tensor([[1],
        [3],
        [5]])

In [105]:
# Reshaping by means of "view". It doesn't change original variable. Performing almost the same function
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
x.view(2,5) # view and reshape are doing similar operation

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [107]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [109]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
x.shape

torch.Size([10])

In [111]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [112]:
z = x.view(2,5)

In [114]:
z # Z is now linked to x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [116]:
x[0] = 9999

In [117]:
x

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [119]:
z # View creates link between source variable and new variable

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [120]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
# INFER what the 2nd dimension should be
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

### Torch arithmetic

In [6]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])
a

tensor([1., 2., 3.])

In [7]:
b

tensor([4., 5., 6.])

In [8]:
a + b # elementwise summation

tensor([5., 7., 9.])

In [10]:
torch.add(a,b) # same way as +

tensor([5., 7., 9.])

In [12]:
a.mul(b) # elementwise multiplication

tensor([ 4., 10., 18.])

In [13]:
a

tensor([1., 2., 3.])

In [14]:
#a = a.mul(b)
a.mul_(b) # Underscroe reassignes the tensor. Change value of a tensor in place

tensor([ 4., 10., 18.])

In [15]:
a

tensor([ 4., 10., 18.])

### Matrix operations

In [17]:
a = torch.tensor([1.,2.,3.])
a

tensor([1., 2., 3.])

In [18]:
b

tensor([4., 5., 6.])

In [19]:
a * b

tensor([ 4., 10., 18.])

In [21]:
a.dot(b) # dot product

tensor(32.)

In [23]:
a = torch.tensor([[0,2,4],[1,3,5]])
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [25]:
b = torch.tensor([[6,7],[8,9],[10,11]])
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [26]:
a.shape

torch.Size([2, 3])

In [27]:
b.shape

torch.Size([3, 2])

In [29]:
torch.mm(a,b) # matrix multiplication

tensor([[56, 62],
        [80, 89]])

In [31]:
a @ b # matrix multiplication as well

tensor([[56, 62],
        [80, 89]])

In [32]:
x = torch.tensor([2.,3.,4.,5.])

In [33]:
x.norm()

tensor(7.3485)

In [36]:
x.numel() # number of elements

4

In [37]:
len(x)

4

In [39]:
len(a) # only # of rows

2

In [41]:
a.numel() # total number of elements inside this tensor

6